name: expense_tracker
description: "A budgeting and expense tracking app with spending categories, charts and budget goals. Include a clean dashboard with key insights. It should include spending categories, charts, and budget goals."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  provider: ^6.1.5+1
  fl_chart: ^1.1.1
  google_fonts: ^6.3.2
  intl: ^0.20.2
  uuid: ^4.5.1
  flutter_colorpicker: ^1.1.0
  go_router: ^16.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
